name: MRPyCM-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - numpy=1.25.1
  - scipy=1.11.1
  - matplotlib=3.7.2
  - qcelemental=0.25.1
  - pip=23.1.2
  - pip:
    - pytest==7.4.0
  
